[project]
name = "intro-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
]

[dependency-groups]
pytorch = [
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]
keras = [
    "keras>=3.9.2",
]
